# image: https://hub.docker.com/r/sscms/core
# src: https://github.com/siteserver/cms/tree/master/docker
# docs: https://sscms.com/docs/v7/getting-started/using-docker.html


version: '3.8'

services:
  sscms:
    image: sscms/core:${APP_VERSION}
    container_name: ${APP_NAME}
    ports:
      - ${APP_HTTP_PORT}:80
    volumes:
      - sscms:/app/wwwroot
    environment:
      - SSCMS_DATABASE_PASSWORD=${DB_MYSQL_PASSWORD}
      - SSCMS_DATABASE_NAME=${DB_MYSQL_NAME}
      - SSCMS_DATABASE_USER=${DB_MYSQL_USER}
      - SSCMS_DATABASE_PORT=${DB_MYSQL_PORT}
      - SSCMS_DATABASE_HOST=mysql
      - SSCMS_SECURITY_KEY=e2a3d303-ac9b-41ff-9154-930710af0845
      - SSCMS_DATABASE_TYPE=MySQL
    depends_on: 
      - mysql
    restart: always

  mysql:
    image: mysql:${DB_MYSQL_VERSION}
    container_name: ${APP_NAME}-mysql
    restart: always
    ports:
     - ${DB_MYSQL_PORT}:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_MYSQL_NAME}
      MYSQL_USER: ${DB_MYSQL_USER}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  sscms:
    driver: local
  mysql:
    driver: local
